# Generated by Django 4.2.30 on 2026-09-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEnvoyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('cle_cible', models.CharField(max_length=100)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification envoyée',
                'verbose_name_plural': 'Notifications envoyées',
                'db_table': 'gimao_notification_envoyee',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationenvoyee',
            constraint=models.UniqueConstraint(fields=('event', 'cle_cible'), name='unique_notification_event_cible'),
        ),
    ]
