name: gimao-dev
services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gimao
      MYSQL_USER: gimao_user
      MYSQL_PASSWORD: gimao_password
    volumes:
      - db_data_dev:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - gimao_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: gimao_user
      PMA_PASSWORD: gimao_password
    ports:
      - "8090:80"
    networks:
      - gimao_network
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - media_data_dev:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=gimao.settings
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=gimao
      - DB_USER=gimao_user
      - DB_PASSWORD=gimao_password
      - LOCUST_PASSWORD=locust123
      - LOCUST_RESPONSABLE_USERNAME=locust_responsable
      - LOCUST_TECHNICIEN_USERNAME=locust_technicien
      - LOCUST_MAGASINIER_USERNAME=locust_magasinier
      - LOCUST_OPERATEUR_USERNAME=locust_operateur
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
    networks:
      - gimao_network
  locust:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - media_data_dev:/app/media
    ports:
      - "8089:8089"
    depends_on:
      - backend
    environment:
      - LOCUST_HOST=http://backend:8000
      - LOCUST_READ_ONLY=true
      - LOCUST_PASSWORD=locust123
      - LOCUST_RESPONSABLE_USERNAME=locust_responsable
      - LOCUST_TECHNICIEN_USERNAME=locust_technicien
      - LOCUST_MAGASINIER_USERNAME=locust_magasinier
      - LOCUST_OPERATEUR_USERNAME=locust_operateur
    command: >
      sh -c "while ! nc -z backend 8000; do sleep 1; done &&
      locust -f /app/locustfile.py --host http://backend:8000"
    networks:
      - gimao_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - VUE_APP_PROXY_TARGET=http://backend:8000
    networks:
      - gimao_network

volumes:
  db_data_dev:
  media_data_dev:

networks:
  gimao_network:
    driver: bridge
