# Generated by Django 4.2.30 on 2026-09-20 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_bontravail_bt_arch_assign_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentVehicule',
            fields=[
                ('demande_intervention', models.OneToOneField(help_text="Demande d'intervention générique dont ce profil complète les données véhicule", on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='incident_vehicule', serialize=False, to='maintenance.demandeintervention')),
                ('type_avarie', models.CharField(choices=[('VOYANT', 'Voyant tableau de bord'), ('BRUIT_ANORMAL', 'Bruit anormal'), ('ACCIDENT_ROUTE', 'Accident de la route'), ('CODE_DEFAUT', 'Code défaut'), ('USURE_SIGNALEE', 'Usure signalée'), ('AUTRE', 'Autre')], help_text="Nature de l'avarie signalée", max_length=20)),
                ('gravite', models.CharField(choices=[('MINEURE', 'Mineure'), ('MODEREE', 'Modérée'), ('CRITIQUE', 'Critique')], default='MINEURE', help_text='Niveau de gravité perçu par le déclarant', max_length=10)),
                ('immobilisation', models.BooleanField(default=False, help_text='Le véhicule est-il immobilisé suite à cet incident ?')),
            ],
            options={
                'verbose_name': 'Incident véhicule',
                'verbose_name_plural': 'Incidents véhicule',
                'db_table': 'gimao_incident_vehicule',
            },
        ),
    ]
