# Generated by Django 4.2.30 on 2026-09-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_incidentvehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('incident_vehicule', models.OneToOneField(help_text='Incident (accident de la route) concerné', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sinistre', serialize=False, to='maintenance.incidentvehicule')),
                ('date_accident', models.DateField(help_text="Date à laquelle l'accident a eu lieu")),
                ('lieu_accident', models.CharField(help_text="Lieu de l'accident", max_length=255)),
                ('tiers_impliques', models.TextField(blank=True, help_text='Description des tiers impliqués', null=True)),
                ('degats_constates', models.TextField(blank=True, help_text='Description des dégâts constatés', null=True)),
                ('numero_declaration_assurance', models.CharField(blank=True, help_text="Numéro de dossier auprès de l'assurance", max_length=100, null=True)),
                ('expertise', models.TextField(blank=True, help_text="Compte-rendu d'expertise", null=True)),
            ],
            options={
                'verbose_name': 'Sinistre',
                'verbose_name_plural': 'Sinistres',
                'db_table': 'gimao_sinistre',
            },
        ),
    ]
