# Generated by Django 4.2.30 on 2026-09-20 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0007_controletechnique_cartegrise'),
        ('maintenance', '0007_sinistre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDefautOBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code DTC normalisé (ex. P0301)', max_length=10)),
                ('description', models.CharField(blank=True, help_text='Description humaine du code', max_length=255, null=True)),
                ('date_lecture', models.DateTimeField(help_text='Date et heure de lecture du code')),
                ('source', models.CharField(choices=[('MANUEL', 'Manuel (valise diagnostic)'), ('AUTOMATIQUE', 'Automatique (boîtier OBD)')], help_text='Origine de la lecture (manuelle ou automatique)', max_length=20)),
                ('incident_vehicule', models.ForeignKey(blank=True, help_text='Incident associé, le cas échéant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_defaut_obd', to='maintenance.incidentvehicule')),
                ('vehicule_profile', models.ForeignKey(help_text='Véhicule sur lequel le code a été relevé', on_delete=django.db.models.deletion.CASCADE, related_name='codes_defaut_obd', to='equipement.vehiculeprofile')),
            ],
            options={
                'verbose_name': 'Code défaut OBD',
                'verbose_name_plural': 'Codes défaut OBD',
                'db_table': 'gimao_code_defaut_obd',
                'ordering': ['-date_lecture'],
                'indexes': [models.Index(fields=['vehicule_profile', '-date_lecture'], name='obd_veh_date_idx')],
            },
        ),
    ]
