# Generated by Django 4.2.30 on 2026-09-19 19:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0005_equipement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='type',
            field=models.CharField(blank=True, choices=[('PEDAGOGIQUE', 'Pédagogique'), ('INFRASTRUCTURE', 'Infrastructure'), ('MECANIQUE', 'Mécanique'), ('ELECTRIQUE', 'Électrique'), ('HYDRAULIQUE', 'Hydraulique'), ('VEHICULE', 'Véhicule'), ('PLURITECHNIQUE', 'Pluritechnique')], help_text="Type d'équipement", max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='VehiculeProfile',
            fields=[
                ('equipement', models.OneToOneField(help_text='Équipement générique dont ce profil complète les données véhicule', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vehicule_profile', serialize=False, to='equipement.equipement')),
                ('vin', models.CharField(help_text="Numéro d'identification du véhicule (VIN), 17 caractères ISO 3779", max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Le VIN doit comporter exactement 17 caractères alphanumériques (hors I, O, Q, exclus par la norme ISO 3779).', regex='^[A-HJ-NPR-Z0-9]{17}$')])),
                ('immatriculation', models.CharField(help_text="Plaque d'immatriculation au format SIV français (AA-123-AA)", max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="L'immatriculation doit respecter le format SIV français : AA-123-AA.", regex='^[A-Z]{2}-\\d{3}-[A-Z]{2}$')])),
                ('genre', models.CharField(choices=[('VL', 'Véhicule léger'), ('PL', 'Poids lourd'), ('UTILITAIRE', 'Utilitaire'), ('REMORQUE', 'Remorque')], help_text='Catégorie du véhicule (VL, PL, utilitaire, remorque)', max_length=20)),
                ('energie', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('ELECTRIQUE', 'Électrique'), ('HYBRIDE', 'Hybride'), ('GPL', 'GPL'), ('AUTRE', 'Autre')], help_text="Type d'énergie/motorisation du véhicule", max_length=20)),
                ('co2', models.PositiveIntegerField(blank=True, help_text='Émissions de CO2 en grammes par kilomètre', null=True)),
                ('puissanceFiscale', models.PositiveIntegerField(blank=True, help_text='Puissance fiscale en chevaux fiscaux', null=True)),
                ('ptac', models.PositiveIntegerField(blank=True, help_text='Poids total autorisé en charge, en kilogrammes', null=True)),
            ],
            options={
                'verbose_name': 'Profil véhicule',
                'verbose_name_plural': 'Profils véhicule',
                'db_table': 'gimao_vehicule_profile',
                'indexes': [models.Index(fields=['immatriculation'], name='vehicule_immat_idx'), models.Index(fields=['vin'], name='vehicule_vin_idx')],
            },
        ),
    ]
