# Generated by Django 4.2.30 on 2026-09-19 21:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0006_alter_equipement_type_vehiculeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passage', models.DateField(help_text='Date à laquelle le contrôle a été effectué')),
                ('date_echeance', models.DateField(help_text="Date d'échéance résultant de ce contrôle (prochain CT ou contre-visite)")),
                ('resultat', models.CharField(choices=[('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('CONTRE_VISITE', 'Contre-visite')], max_length=20)),
                ('centre_controle', models.CharField(blank=True, help_text='Nom du centre de contrôle technique', max_length=200, null=True)),
                ('vehicule_profile', models.ForeignKey(help_text='Véhicule contrôlé', on_delete=django.db.models.deletion.CASCADE, related_name='controles_techniques', to='equipement.vehiculeprofile')),
            ],
            options={
                'verbose_name': 'Contrôle technique',
                'verbose_name_plural': 'Contrôles techniques',
                'db_table': 'gimao_controle_technique',
                'ordering': ['-date_passage'],
                'indexes': [models.Index(fields=['vehicule_profile', '-date_passage'], name='ct_veh_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarteGrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(help_text='Immatriculation figurant sur ce certificat', max_length=9, validators=[django.core.validators.RegexValidator(message="L'immatriculation doit respecter le format SIV français : AA-123-AA.", regex='^[A-Z]{2}-\\d{3}-[A-Z]{2}$')])),
                ('titulaire', models.CharField(help_text="Titulaire du certificat d'immatriculation", max_length=200)),
                ('date_premiere_mise_circulation', models.DateField(help_text='Date de première mise en circulation du véhicule')),
                ('date_emission', models.DateField(help_text="Date d'émission de ce certificat")),
                ('vehicule_profile', models.ForeignKey(help_text='Véhicule concerné par ce certificat', on_delete=django.db.models.deletion.CASCADE, related_name='cartes_grises', to='equipement.vehiculeprofile')),
            ],
            options={
                'verbose_name': 'Carte grise',
                'verbose_name_plural': 'Cartes grises',
                'db_table': 'gimao_carte_grise',
                'ordering': ['-date_emission'],
                'indexes': [models.Index(fields=['vehicule_profile', '-date_emission'], name='cg_veh_date_idx')],
            },
        ),
    ]
